/*
 * SPDX-License-Identifier: AGPL-3.0-or-later
 * SPDX-FileCopyrightText: 2025 Seventeen Sierra LLC
 */

'use client';

import { Badge, Button, CheckCircle2, Download, Maximize2 } from '@17sierra/ui';
import type { AnalysisResults } from '@/components/results/types';

/**
 * Report data structure
 */
export interface ReportData {
  /** Unique report identifier */
  id: string;
  /** Report title */
  title: string;
  /** Report reference number */
  reference: string;
  /** Generation timestamp */
  generatedAt: Date;
  /** Analysis results data */
  analysisResults?: AnalysisResults;
  /** Overall compliance score (0-100) */
  complianceScore: number;
  /** Report status */
  status: 'generating' | 'ready' | 'error';
}

/**
 * Report Preview Component Props
 */
export interface ReportPreviewProps {
  /** Whether the preview panel is visible */
  isVisible: boolean;
  /** Report data to display */
  reportData?: ReportData;
  /** Whether the report is being generated */
  isGenerating?: boolean;
  /** Callback when user downloads the report */
  onDownload?: (format: 'pdf' | 'docx' | 'html') => void;
  /** Callback when user opens report in fullscreen */
  onFullscreen?: () => void;
  /** Callback when user shares the report */
  onShare?: () => void;
  /** Additional CSS classes */
  className?: string;
}

/**
 * Report Preview Component
 *
 * Displays a live preview of the compliance analysis report with
 * options for download, fullscreen viewing, and sharing.
 *
 * Features:
 * - Real-time report generation preview
 * - Multiple export formats (PDF, DOCX, HTML)
 * - Fullscreen viewing mode
 * - Professional report formatting
 * - Compliance score visualization
 */
const ReportPreview: React.FC<ReportPreviewProps> = ({
  isVisible,
  reportData: _reportData,
  isGenerating: _isGenerating = false,
  onDownload: _onDownload,
  onFullscreen: _onFullscreen,
  onShare: _onShare,
  className = '',
}) => {
  if (!isVisible) return null;

  return (
    <div className="flex-1 bg-gray-50 border-l border-gray-200 h-full flex flex-col animate-in slide-in-from-right duration-300">
      <div className="h-16 bg-white border-b border-gray-200 flex items-center justify-between px-4 shrink-0">
        <div className="font-semibold text-slate-800 text-sm">Compliance Report Preview</div>
        <div className="flex gap-2">
          <Button variant="outline" size="sm">
            <Maximize2 size={12} /> Fullscreen
          </Button>
          <Button size="sm">
            <Download size={12} /> Download PDF
          </Button>
        </div>
      </div>

      <div className="flex-1 p-4 md:p-8 overflow-y-auto">
        <div className="bg-white shadow-lg rounded-sm min-h-[800px] w-full max-w-[800px] mx-auto p-8 md:p-12 relative">
          <div className="flex justify-between items-start mb-8 border-b border-gray-100 pb-8">
            <div>
              <h1 className="text-2xl font-bold text-slate-900 mb-2">
                Compliance Validation Report
              </h1>
              <p className="text-gray-500 text-sm">Generated by ATARC Compliance Agent</p>
            </div>
            <div className="text-right">
              <div className="text-sm font-bold text-slate-900">Ref: PROP-2024-001</div>
              <div className="text-sm text-gray-500">Dec 04, 2025</div>
            </div>
          </div>

          <div className="mb-8">
            <div className="flex items-center gap-2 mb-4">
              <div className="h-2 w-2 rounded-full bg-green-500"></div>
              <h3 className="font-bold text-slate-800 uppercase tracking-wide text-sm">
                Executive Summary
              </h3>
            </div>
            <p className="text-sm text-gray-600 leading-relaxed mb-4">
              The submitted proposal "Cloud Modernization Initiative" has been analyzed against the
              current Federal Acquisition Regulation (FAR) and Defense Federal Acquisition
              Regulation Supplement (DFARS). The document scored a{' '}
              <strong>92% compliance rating</strong>.
            </p>
            <div className="bg-green-50 border border-green-100 rounded-lg p-4 flex gap-3 items-start">
              <CheckCircle2 size={20} className="text-green-600 mt-0.5 shrink-0" />
              <div className="text-sm text-green-800">
                <strong className="text-green-900">Status: Compliant</strong>
                <br />
                This proposal meets all mandatory formatting and inclusion requirements for the
                targeted solicitation.
              </div>
            </div>
          </div>

          <div className="mb-8">
            <div className="flex items-center gap-2 mb-4">
              <div className="h-2 w-2 rounded-full bg-primary"></div>
              <h3 className="font-bold text-slate-800 uppercase tracking-wide text-sm">
                Key Findings
              </h3>
            </div>

            <div className="space-y-3">
              <div className="border border-gray-200 rounded-lg p-3">
                <div className="flex justify-between items-center mb-1">
                  <span className="font-semibold text-sm text-slate-700">FAR 52.204-24 Check</span>
                  <Badge
                    variant="secondary"
                    className="bg-green-100 text-green-800 border-green-200"
                  >
                    PASS
                  </Badge>
                </div>
                <p className="text-xs text-gray-500">
                  Representation Regarding Certain Telecommunications and Video Surveillance
                  Services or Equipment is present and signed.
                </p>
              </div>

              <div className="border border-gray-200 rounded-lg p-3">
                <div className="flex justify-between items-center mb-1">
                  <span className="font-semibold text-sm text-slate-700">
                    Biosketch Format (SciENcv)
                  </span>
                  <Badge
                    variant="secondary"
                    className="bg-green-100 text-green-800 border-green-200"
                  >
                    PASS
                  </Badge>
                </div>
                <p className="text-xs text-gray-500">
                  All personnel biosketches adhere to the required SciENcv structure.
                </p>
              </div>

              <div className="border border-yellow-200 rounded-lg p-3 bg-yellow-50/50">
                <div className="flex justify-between items-center mb-1">
                  <span className="font-semibold text-sm text-yellow-900">
                    Budget Justification
                  </span>
                  <Badge
                    variant="secondary"
                    className="bg-yellow-100 text-yellow-800 border-yellow-200"
                  >
                    WARNING
                  </Badge>
                </div>
                <p className="text-xs text-yellow-700">
                  Budget justification length is exactly at the limit (5 pages). Review for brevity
                  recommended.
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default ReportPreview;
