'use client';

import { Badge, Button } from '@17sierra/ui';
import {
  AlertTriangle,
  CalendarIcon,
  CheckCircle2,
  Download,
  FileText,
  Maximize2,
} from '@17sierra/ui';
import type { AnalysisResults } from '@/components/results/types';

type ReportPreviewProps = {
  isVisible: boolean;
  results?: AnalysisResults | null;
};

const ReportPreview = ({ isVisible, results }: ReportPreviewProps) => {
  if (!isVisible) return null;

  // Use results if available, otherwise fallback (or show nothing/loading if needed)
  if (!results) return null;

  return (
    <div className="flex-1 bg-slate-50 border-l border-gray-200 h-full flex flex-col animate-in slide-in-from-right duration-500 z-10 shadow-xl max-w-[50%] min-w-[500px]">
      <div className="h-16 bg-white border-b border-gray-200 flex items-center justify-between px-6 shrink-0 z-20 shadow-sm">
        <div className="flex items-center gap-2">
          <FileText size={18} className="text-blue-600" />
          <div className="font-semibold text-slate-800 text-sm">Compliance Report Preview</div>
        </div>
        <div className="flex gap-2">
          <Button variant="outline" size="sm" className="h-8 text-xs gap-1.5 hidden md:flex">
            <Maximize2 size={12} /> Fullscreen
          </Button>
          <Button size="sm" className="h-8 text-xs gap-1.5 bg-slate-900 hover:bg-slate-800">
            <Download size={12} /> Download PDF
          </Button>
        </div>
      </div>

      <div className="flex-1 p-6 md:p-8 overflow-y-auto bg-gray-50/50">
        <div className="bg-white shadow-lg rounded-sm w-full max-w-[800px] mx-auto p-10 md:p-14 relative ring-1 ring-gray-900/5">
          {/* Document Header */}
          <div className="flex justify-between items-start mb-10 border-b-2 border-slate-900 pb-6">
            <div>
              <h1 className="text-3xl font-bold text-slate-900 mb-2 tracking-tight">
                Compliance Validation Report
              </h1>
              <p className="text-gray-500 text-sm font-medium">
                Generated by ATARC Compliance Agent
              </p>
            </div>
            <div className="text-right">
              <div className="text-sm font-bold text-slate-900 bg-slate-100 px-3 py-1 rounded-md inline-block mb-1">
                Ref: PROP-2024-001
              </div>
              <div className="text-sm text-gray-500 flex items-center justify-end gap-1.5">
                <CalendarIcon size={12} />{' '}
                {new Date().toLocaleDateString('en-US', {
                  month: 'short',
                  day: '2-digit',
                  year: 'numeric',
                })}
              </div>
            </div>
          </div>

          {/* Executive Summary Section */}
          <div className="mb-10">
            <div className="flex items-center gap-3 mb-4">
              <div className="h-8 w-1 bg-blue-600 rounded-full"></div>
              <h3 className="font-bold text-slate-800 uppercase tracking-wider text-sm">
                Executive Summary
              </h3>
            </div>
            <p className="text-sm text-gray-600 leading-relaxed mb-6 font-serif text-justify">
              The submitted proposal has been analyzed against the current Federal Acquisition
              Regulation (FAR) and Defense Federal Acquisition Regulation Supplement (DFARS). The
              document scored a{' '}
              <span
                className={`px-1 py-0.5 rounded font-bold ${results.overallScore >= 90
                  ? 'bg-green-100 text-green-800'
                  : results.overallScore >= 70
                    ? 'bg-yellow-100 text-yellow-800'
                    : 'bg-red-100 text-red-800'
                  }`}
              >
                {results.overallScore}% compliance rating
              </span>
              .
            </p>

            <div
              className={`border rounded-lg p-5 flex gap-4 items-start shadow-sm ${results.status === 'pass'
                ? 'bg-green-50 border-green-200'
                : results.status === 'warning'
                  ? 'bg-yellow-50 border-yellow-200'
                  : 'bg-red-50 border-red-200'
                }`}
            >
              <div
                className={`p-2 rounded-full shrink-0 ${results.status === 'pass'
                  ? 'bg-green-100'
                  : results.status === 'warning'
                    ? 'bg-yellow-100'
                    : 'bg-red-100'
                  }`}
              >
                {results.status === 'pass' ? (
                  <CheckCircle2 size={24} className="text-green-600" />
                ) : (
                  <AlertTriangle
                    size={24}
                    className={results.status === 'warning' ? 'text-yellow-600' : 'text-red-600'}
                  />
                )}
              </div>
              <div>
                <strong
                  className={`block mb-1 text-base ${results.status === 'pass'
                    ? 'text-green-900'
                    : results.status === 'warning'
                      ? 'text-yellow-900'
                      : 'text-red-900'
                    }`}
                >
                  Status: {results.status.toUpperCase()}
                </strong>
                <div
                  className={`text-sm leading-relaxed ${results.status === 'pass'
                    ? 'text-green-800'
                    : results.status === 'warning'
                      ? 'text-yellow-800'
                      : 'text-red-800'
                    }`}
                >
                  {results.status === 'pass'
                    ? 'This proposal meets all mandatory formatting and inclusion requirements for the targeted solicitation. No critical blocking issues were found.'
                    : `This proposal has identified ${results.status === 'warning' ? 'warnings' : 'critical issues'} that require attention.`}
                </div>
              </div>
            </div>
          </div>

          {/* Key Findings Section */}
          <div className="mb-8">
            <div className="flex items-center gap-3 mb-5">
              <div className="h-8 w-1 bg-slate-800 rounded-full"></div>
              <h3 className="font-bold text-slate-800 uppercase tracking-wider text-sm">
                Detailed Findings
              </h3>
            </div>

            <div className="space-y-4">
              {results.issues.length === 0 ? (
                <div className="text-center p-8 text-gray-500 italic">No issues found.</div>
              ) : (
                results.issues.map((issue) => (
                  <div
                    key={issue.id}
                    className={`group border rounded-lg p-4 hover:shadow-md transition-all ${issue.severity === 'critical'
                      ? 'border-red-200 bg-red-50/30'
                      : issue.severity === 'warning'
                        ? 'border-yellow-200 bg-yellow-50/30'
                        : 'border-gray-200 bg-white hover:border-blue-300'
                      }`}
                  >
                    <div className="flex justify-between items-center mb-2">
                      <div className="flex items-center gap-2">
                        {issue.regulation && (
                          <span className="bg-gray-100 text-gray-600 text-[10px] font-mono px-1.5 py-0.5 rounded border border-gray-200">
                            {issue.regulation}
                          </span>
                        )}
                        <span className="font-semibold text-sm text-slate-800">{issue.title}</span>
                      </div>
                      <Badge
                        variant="secondary"
                        className={`font-bold ${issue.severity === 'critical'
                          ? 'bg-red-100 text-red-700 border-red-200'
                          : issue.severity === 'warning'
                            ? 'bg-yellow-100 text-yellow-800 border-yellow-200'
                            : 'bg-blue-100 text-blue-700 border-blue-200'
                          }`}
                      >
                        {issue.severity.toUpperCase()}
                      </Badge>
                    </div>

                    <div
                      className={`gap-2 items-start pl-1 border-l-2 ml-1 ${issue.severity === 'critical'
                        ? 'border-red-300'
                        : issue.severity === 'warning'
                          ? 'border-yellow-300'
                          : 'border-gray-200'
                        }`}
                    >
                      <p className="text-xs text-gray-600 mb-1">{issue.description}</p>
                      {issue.remediation && (
                        <p className="text-xs text-slate-500 italic mt-1 bg-white/50 p-1.5 rounded">
                          Recommendation: {issue.remediation}
                        </p>
                      )}
                    </div>
                  </div>
                ))
              )}
            </div>
          </div>

          <div className="mt-12 text-center border-t border-gray-100 pt-8 text-[10px] text-gray-400 uppercase tracking-widest">
            CONFIDENTIAL - PROPRIETARY INFORMATION - DO NOT DISTRIBUTE
          </div>
        </div>
      </div>
    </div>
  );
};

export default ReportPreview;
