'use client';

import { AlertTriangle, Calendar, CheckCircle2, Download, FileText, Maximize2 } from 'lucide-react';
import { Badge, Button } from '@17sierra/ui';

type ReportPreviewProps = {
  isVisible: boolean;
};

const ReportPreview = ({ isVisible }: ReportPreviewProps) => {
  if (!isVisible) return null;

  return (
    <div className="flex-1 bg-slate-50 border-l border-gray-200 h-full flex flex-col animate-in slide-in-from-right duration-500 z-10 shadow-xl max-w-[50%] min-w-[500px]">
      <div className="h-16 bg-white border-b border-gray-200 flex items-center justify-between px-6 shrink-0 z-20 shadow-sm">
        <div className="flex items-center gap-2">
          <FileText size={18} className="text-blue-600" />
          <div className="font-semibold text-slate-800 text-sm">Compliance Report Preview</div>
        </div>
        <div className="flex gap-2">
          <Button variant="outline" size="sm" className="h-8 text-xs gap-1.5 hidden md:flex">
            <Maximize2 size={12} /> Fullscreen
          </Button>
          <Button size="sm" className="h-8 text-xs gap-1.5 bg-slate-900 hover:bg-slate-800">
            <Download size={12} /> Download PDF
          </Button>
        </div>
      </div>

      <div className="flex-1 p-6 md:p-8 overflow-y-auto bg-gray-50/50">
        <div className="bg-white shadow-lg rounded-sm w-full max-w-[800px] mx-auto p-10 md:p-14 relative ring-1 ring-gray-900/5">
          {/* Document Header */}
          <div className="flex justify-between items-start mb-10 border-b-2 border-slate-900 pb-6">
            <div>
              <h1 className="text-3xl font-bold text-slate-900 mb-2 tracking-tight">
                Compliance Validation Report
              </h1>
              <p className="text-gray-500 text-sm font-medium">
                Generated by ATARC Compliance Agent
              </p>
            </div>
            <div className="text-right">
              <div className="text-sm font-bold text-slate-900 bg-slate-100 px-3 py-1 rounded-md inline-block mb-1">
                Ref: PROP-2024-001
              </div>
              <div className="text-sm text-gray-500 flex items-center justify-end gap-1.5">
                <Calendar size={12} /> Dec 04, 2025
              </div>
            </div>
          </div>

          {/* Executive Summary Section */}
          <div className="mb-10">
            <div className="flex items-center gap-3 mb-4">
              <div className="h-8 w-1 bg-blue-600 rounded-full"></div>
              <h3 className="font-bold text-slate-800 uppercase tracking-wider text-sm">
                Executive Summary
              </h3>
            </div>
            <p className="text-sm text-gray-600 leading-relaxed mb-6 font-serif text-justify">
              The submitted proposal{' '}
              <strong className="text-slate-900">"Cloud Modernization Initiative"</strong> has been
              analyzed against the current Federal Acquisition Regulation (FAR) and Defense Federal
              Acquisition Regulation Supplement (DFARS). The document scored a{' '}
              <span className="bg-green-100 text-green-800 px-1 py-0.5 rounded font-bold">
                92% compliance rating
              </span>
              .
            </p>

            <div className="bg-green-50 border border-green-200 rounded-lg p-5 flex gap-4 items-start shadow-sm">
              <div className="bg-green-100 p-2 rounded-full shrink-0">
                <CheckCircle2 size={24} className="text-green-600" />
              </div>
              <div>
                <strong className="text-green-900 block mb-1 text-base">Status: Compliant</strong>
                <div className="text-sm text-green-800 leading-relaxed">
                  This proposal meets all mandatory formatting and inclusion requirements for the
                  targeted solicitation. No critical blocking issues were found.
                </div>
              </div>
            </div>
          </div>

          {/* Key Findings Section */}
          <div className="mb-8">
            <div className="flex items-center gap-3 mb-5">
              <div className="h-8 w-1 bg-slate-800 rounded-full"></div>
              <h3 className="font-bold text-slate-800 uppercase tracking-wider text-sm">
                Detailed Findings
              </h3>
            </div>

            <div className="space-y-4">
              {/* Item 1 */}
              <div className="group border border-gray-200 rounded-lg p-4 hover:border-blue-300 hover:shadow-md transition-all bg-white">
                <div className="flex justify-between items-center mb-2">
                  <div className="flex items-center gap-2">
                    <span className="bg-gray-100 text-gray-600 text-[10px] font-mono px-1.5 py-0.5 rounded border border-gray-200">
                      FAR 52.204-24
                    </span>
                    <span className="font-semibold text-sm text-slate-800">
                      Telecommunications Representation
                    </span>
                  </div>
                  <Badge
                    variant="secondary"
                    className="bg-green-100 text-green-700 border-green-200 font-bold hover:bg-green-100"
                  >
                    PASS
                  </Badge>
                </div>
                <p className="text-xs text-gray-500 pl-1 border-l-2 border-gray-200 ml-1">
                  Representation Regarding Certain Telecommunications and Video Surveillance
                  Services or Equipment is present and signed by authorized representative.
                </p>
              </div>

              {/* Item 2 */}
              <div className="group border border-gray-200 rounded-lg p-4 hover:border-blue-300 hover:shadow-md transition-all bg-white">
                <div className="flex justify-between items-center mb-2">
                  <div className="flex items-center gap-2">
                    <span className="bg-gray-100 text-gray-600 text-[10px] font-mono px-1.5 py-0.5 rounded border border-gray-200">
                      FORMAT
                    </span>
                    <span className="font-semibold text-sm text-slate-800">
                      Biosketch Format (SciENcv)
                    </span>
                  </div>
                  <Badge
                    variant="secondary"
                    className="bg-green-100 text-green-700 border-green-200 font-bold hover:bg-green-100"
                  >
                    PASS
                  </Badge>
                </div>
                <p className="text-xs text-gray-500 pl-1 border-l-2 border-gray-200 ml-1">
                  All personnel biosketches adhere to the required SciENcv structure and page
                  limits.
                </p>
              </div>

              {/* Item 3 */}
              <div className="group border border-yellow-200 rounded-lg p-4 bg-yellow-50/30 hover:shadow-md transition-all">
                <div className="flex justify-between items-center mb-2">
                  <div className="flex items-center gap-2">
                    <span className="bg-yellow-100 text-yellow-800 text-[10px] font-mono px-1.5 py-0.5 rounded border border-yellow-200">
                      REVIEW
                    </span>
                    <span className="font-semibold text-sm text-yellow-900">
                      Budget Justification
                    </span>
                  </div>
                  <Badge
                    variant="secondary"
                    className="bg-yellow-100 text-yellow-800 border-yellow-200 font-bold hover:bg-yellow-100"
                  >
                    WARNING
                  </Badge>
                </div>
                <div className="flex gap-2 items-start pl-1 border-l-2 border-yellow-300 ml-1">
                  <AlertTriangle size={14} className="text-yellow-600 mt-0.5" />
                  <p className="text-xs text-yellow-800">
                    Budget justification length is exactly at the limit (5 pages). Review for
                    brevity recommended to avoid potential truncation checks.
                  </p>
                </div>
              </div>
            </div>
          </div>

          <div className="mt-12 text-center border-t border-gray-100 pt-8 text-[10px] text-gray-400 uppercase tracking-widest">
            CONFIDENTIAL - PROPRIETARY INFORMATION - DO NOT DISTRIBUTE
          </div>
        </div>
      </div>
    </div>
  );
};

export default ReportPreview;
